"""Monte-Carlo process simulation — port of SimulationEngine.swift.

A Markov model is fitted to the observed directly-follows graph; journeys are
then generated by random walk with lognormal edge durations and Poisson arrivals.
No database writes are involved.
"""

from __future__ import annotations

import math
import random
from collections import defaultdict
from datetime import timedelta

from ..models import (
    ProcessGraph,
    ProcessTransition,
    SimulatedEvent,
    SimulationConfig,
    SimulationResult,
    SimulationVariant,
    StepInfo,
)


class MarkovModel:
    """Transition probabilities, edge-duration distributions and entry points."""

    def __init__(
        self,
        graph: ProcessGraph,
        step_infos: dict[str, StepInfo],
        excluded: set[str],
    ) -> None:
        # 1. Entry points come from the ORIGINAL graph. Deriving them after
        #    exclusions would make any step that only received edges from an
        #    excluded step look like a process entry point.
        orig_in: dict[str, int] = defaultdict(int)
        orig_out: dict[str, int] = defaultdict(int)
        for t in graph.transitions:
            orig_in[t.toStep] += t.occurrences
            orig_out[t.fromStep] += t.occurrences

        start_set = {
            step for step, out in orig_out.items() if out and orig_in[step] / out < 0.2
        }
        if not start_set and orig_out:
            start_set = {max(orig_out.items(), key=lambda kv: kv[1])[0]}
        start_set -= excluded

        # 2. Apply exclusions.
        filtered = [
            t
            for t in graph.transitions
            if t.fromStep not in excluded and t.toStep not in excluded
        ]

        # 3. BFS reachability from the true start steps prunes anything that
        #    became disconnected.
        adjacency: dict[str, list[str]] = defaultdict(list)
        for t in filtered:
            adjacency[t.fromStep].append(t.toStep)

        reachable: set[str] = set()
        queue = list(start_set)
        while queue:
            step = queue.pop(0)
            if step in reachable:
                continue
            reachable.add(step)
            queue.extend(n for n in adjacency[step] if n not in reachable)

        valid = [
            t for t in filtered if t.fromStep in reachable and t.toStep in reachable
        ]

        self.step_infos = {k: v for k, v in step_infos.items() if k in reachable}

        # 4. Cumulative transition probabilities per source step.
        out_edges: dict[str, list[tuple[str, int]]] = defaultdict(list)
        for t in valid:
            out_edges[t.fromStep].append((t.toStep, t.occurrences))

        self.transitions: dict[str, list[tuple[str, float]]] = {}
        for frm, tos in out_edges.items():
            total = float(sum(count for _, count in tos))
            if total <= 0:
                continue
            cumulative = 0.0
            entries: list[tuple[str, float]] = []
            for to, count in tos:
                cumulative += count / total
                entries.append((to, cumulative))
            self.transitions[frm] = entries

        # 5. Lognormal duration parameters per edge (method of moments).
        self.duration_params: dict[str, tuple[float, float]] = {}
        for t in valid:
            key = f"{t.fromStep}→{t.toStep}"
            avg = t.avgSecs
            if avg and avg > 0:
                sd = t.stdDevSecs
                if sd and sd > 0:
                    variance = sd * sd
                    mu = math.log(avg * avg / math.sqrt(avg * avg + variance))
                    sigma = math.sqrt(math.log(1.0 + variance / (avg * avg)))
                    self.duration_params[key] = (mu, sigma)
                else:
                    self.duration_params[key] = (math.log(avg), 0.0)
            else:
                self.duration_params[key] = (math.log(3600.0), 0.5)

        # 6. Start weights re-derived from the pruned graph so an excluded step's
        #    share is redistributed rather than left as a gap.
        pruned_out: dict[str, int] = defaultdict(int)
        for t in valid:
            pruned_out[t.fromStep] += t.occurrences

        valid_start = [s for s in start_set if s in pruned_out]
        start_total = float(sum(pruned_out[s] for s in valid_start))
        self.start_steps: list[tuple[str, float]] = [
            (s, pruned_out[s] / max(start_total, 1.0)) for s in valid_start
        ]

    def sample_start_step(self) -> str | None:
        if not self.start_steps:
            return None
        r = random.random()
        cumulative = 0.0
        for step, weight in self.start_steps:
            cumulative += weight
            if r <= cumulative:
                return step
        return self.start_steps[-1][0]

    def sample_next_step(self, step: str) -> str | None:
        entries = self.transitions.get(step)
        if not entries:
            return None
        r = random.random()
        for nxt, cum_prob in entries:
            if r <= cum_prob:
                return nxt
        return entries[-1][0]

    def sample_duration(self, frm: str, to: str) -> float:
        params = self.duration_params.get(f"{frm}→{to}")
        if params is None:
            return 3600.0
        mu, sigma = params
        if sigma <= 0:
            return max(60.0, math.exp(mu))
        # Box–Muller transform → standard normal → lognormal
        u1 = random.uniform(1e-10, 1.0)
        u2 = random.random()
        z = math.sqrt(-2.0 * math.log(u1)) * math.cos(2.0 * math.pi * u2)
        return max(60.0, math.exp(mu + sigma * z))


def build_graph(
    events: list[SimulatedEvent], step_infos: dict[str, StepInfo]
) -> ProcessGraph:
    """Aggregate a simulated event log back into a directly-follows graph."""
    by_journey: dict[str, list[SimulatedEvent]] = defaultdict(list)
    for e in events:
        by_journey[e.journeyId].append(e)

    stats: dict[tuple[str, str], dict[str, float]] = {}
    step_set: set[str] = set()

    for evs in by_journey.values():
        ordered = sorted(evs, key=lambda e: e.timestamp)
        for i, event in enumerate(ordered):
            step_set.add(event.step)
            if i + 1 >= len(ordered):
                continue
            secs = (ordered[i + 1].timestamp - event.timestamp).total_seconds()
            key = (event.step, ordered[i + 1].step)
            s = stats.setdefault(
                key, {"count": 0, "total": 0.0, "min": math.inf, "max": -math.inf, "sq": 0.0}
            )
            s["count"] += 1
            s["total"] += secs
            s["min"] = min(s["min"], secs)
            s["max"] = max(s["max"], secs)
            s["sq"] += secs * secs

    transitions: list[ProcessTransition] = []
    for (frm, to), s in stats.items():
        count = int(s["count"])
        avg = s["total"] / count
        std = math.sqrt(max(0.0, s["sq"] / count - avg * avg))
        transitions.append(
            ProcessTransition(
                fromStep=frm,
                toStep=to,
                occurrences=count,
                avgSecs=avg,
                minSecs=s["min"] if math.isfinite(s["min"]) else None,
                maxSecs=s["max"] if math.isfinite(s["max"]) else None,
                stdDevSecs=std if std > 0 else None,
            )
        )

    steps: dict[str, StepInfo] = {}
    for name in step_set:
        steps[name] = step_infos.get(name) or StepInfo(
            step=name, description=name, bgColor="blue", fgColor="white"
        )
    return ProcessGraph(steps=steps, transitions=transitions)


def _simulate_journey(
    model: MarkovModel, start_time, journey_id: str, max_steps: int
) -> tuple[list[SimulatedEvent], str, float] | None:
    first = model.sample_start_step()
    if first is None:
        return None

    current_step = first
    current_time = start_time
    events = [SimulatedEvent(journeyId=journey_id, step=first, timestamp=current_time)]
    path_steps = [first]

    for _ in range(max_steps):
        info = model.step_infos.get(current_step)
        if info is not None and info.endOfProcess:
            break
        nxt = model.sample_next_step(current_step)
        if nxt is None:
            break
        current_time = current_time + timedelta(
            seconds=model.sample_duration(current_step, nxt)
        )
        current_step = nxt
        path_steps.append(nxt)
        events.append(
            SimulatedEvent(journeyId=journey_id, step=nxt, timestamp=current_time)
        )
        nxt_info = model.step_infos.get(nxt)
        if nxt_info is not None and nxt_info.endOfProcess:
            break

    cycle_secs = (current_time - start_time).total_seconds()
    return events, " → ".join(path_steps), cycle_secs


def simulate(
    graph: ProcessGraph, step_infos: dict[str, StepInfo], config: SimulationConfig
) -> SimulationResult:
    model = MarkovModel(graph, step_infos, set(config.excludedSteps))
    if not model.start_steps:
        return SimulationResult()

    all_events: list[SimulatedEvent] = []
    cycle_secs: list[float] = []
    variant_map: dict[str, tuple[int, float]] = {}

    lambda_secs = config.avgInterArrivalHours * 3600.0
    arrival_time = config.startDate
    required = set(config.requiredSteps)

    generated = 0
    max_attempts = max(config.journeyCount * 20, 1000)

    for _ in range(max_attempts):
        if generated >= config.journeyCount:
            break
        # Exponential inter-arrival times (Poisson arrival process)
        u = random.uniform(1e-10, 1.0)
        arrival_time = arrival_time + timedelta(seconds=-lambda_secs * math.log(u))

        journey = _simulate_journey(
            model, arrival_time, f"SIM-{generated + 1}", config.maxStepsPerJourney
        )
        if journey is None:
            continue
        events, path, cycle = journey

        if required and not required.issubset({e.step for e in events}):
            continue

        all_events.extend(events)
        cycle_secs.append(cycle)
        prev_count, prev_total = variant_map.get(path, (0, 0.0))
        variant_map[path] = (prev_count + 1, prev_total + cycle)
        generated += 1

    if not cycle_secs:
        return SimulationResult()

    avg = sum(cycle_secs) / len(cycle_secs)
    variance = sum((c - avg) ** 2 for c in cycle_secs) / len(cycle_secs)
    total = float(generated)

    variants = sorted(
        (
            SimulationVariant(
                path=path,
                count=count,
                percentage=count / total * 100.0,
                avgCycleTimeSecs=(total_secs / count) if count else 0.0,
            )
            for path, (count, total_secs) in variant_map.items()
        ),
        key=lambda v: v.count,
        reverse=True,
    )

    return SimulationResult(
        events=all_events,
        variants=variants,
        cycleTimes=cycle_secs,
        simProcessGraph=build_graph(all_events, step_infos),
        totalJourneys=generated,
        avgCycleTimeSecs=avg,
        minCycleTimeSecs=min(cycle_secs),
        maxCycleTimeSecs=max(cycle_secs),
        stdDevCycleTimeSecs=math.sqrt(variance),
    )
